apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-frontend
  template:
    metadata:
      labels:
        app: arcadia-frontend
    spec:
      containers:
        - name: arcadia-frontend
          image: registry.gitlab.com/arcadia-crypto/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: arcadia-frontend
