apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-stock-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-stock-transaction
  template:
    metadata:
      labels:
        app: arcadia-stock-transaction
    spec:
      containers:
        - name: arcadia-stock-transaction
          image: registry.gitlab.com/arcadia-crypto/backend/stock-transaction
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-stock-transaction
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: arcadia-stock-transaction
