apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-users
  template:
    metadata:
      labels:
        app: arcadia-users
    spec:
      containers:
        - name: arcadia-users
          image: sorinboia/arcadia-users:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-login
  template:
    metadata:
      labels:
        app: arcadia-login
    spec:
      containers:
        - name: arcadia-login
          image: sorinboia/arcadia-login:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-cash-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-cash_transfer
  template:
    metadata:
      labels:
        app: arcadia-cash_transfer
    spec:
      containers:
        - name: arcadia-users
          image: sorinboia/arcadia-cash_transfer:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-users
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-users

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-login
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-login

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-cash
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-cash_transfer

---

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: arcadia
spec:
  host: localhost
  upstreams:
    - name: arcadia-users
      service: arcadia-users
      port: 80
    - name: arcadia-login
      service: arcadia-login
      port: 80
  routes:
    - path: /v1/user
      action:
        pass: arcadia-users
    - path: /v1/login
      action:
        pass: arcadia-login