apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-db
  template:
    metadata:
      labels:
        app: arcadia-db
    spec:
      containers:
        - name: arcadia-db
          image: registry.gitlab.com/arcadia-crypto/backend/arcadia-db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: arcadia-db
